In [5]:
5*5


25

In [6]:
x = 5

In [7]:
y = 4

In [8]:
x * y

20

In [9]:
x = 6


In [10]:
x * y

24

In [11]:
ilk = 10

In [12]:
son = 20

In [13]:
ilk + son

30

In [14]:
ilk / son

0.5

In [15]:
son / ilk

2.0

In [16]:
bol = son/ilk

In [17]:
bol

2.0

x

In [18]:
x

6

karesini alma
  
  

In [19]:

x ** 2

36

In [20]:
# Remainder - Kalanını bulma
10 % 2

0

In [21]:
kullaniciYasi=input("Yaşınız")

In [22]:
kullaniciYasi

'2'

In [23]:
kullaniciYasi * 50

'22222222222222222222222222222222222222222222222222'

In [24]:
kullaniciYasi = "otuz"

In [25]:
kullaniciYasi

'otuz'

In [26]:
kullaniciYasi.count

<function str.count>

In [27]:
len(kullaniciYasi)

4

In [28]:
sayi = "123456"

In [29]:
sayi[2:]

'3456'

In [30]:
test = "abcdef"

In [31]:
test

'abcdef'

In [32]:
test[:3]

'abc'

In [33]:
test[3:]

'def'

In [34]:
#  Slicing

In [35]:
benimListem = [10,20,30,40,50]

In [36]:
if 10 in benimListem:
  print("evet")

evet


In [37]:
benimListem[0] * 5 /3

16.666666666666668

In [38]:

for numara in benimListem:
  print(numara / 3)

3.3333333333333335
6.666666666666667
10.0
13.333333333333334
16.666666666666668


In [39]:
for num in benimListem:
  yeniNum = num - 2 /10
  print(yeniNum)

9.8
19.8
29.8
39.8
49.8


In [40]:
liste = [1,2,3,4,5,6]
for rakam in liste:
  if rakam % 2 ==0:
    print(rakam)

2
4
6


In [41]:
yeniString = "asd"

In [42]:
for harf in yeniString:
  print(harf)

a
s
d


In [43]:
myTuple= (12,2,3,4,5,6)

for eleman in myTuple:
  print(eleman -10)

2
-8
-7
-6
-5
-4


In [44]:
koordinatList = [(10.2,15.2), (30.2,102.3), (94,186)]
type(koordinatList[0])
for eleman in koordinatList:
  print(eleman)

(10.2, 15.2)
(30.2, 102.3)
(94, 186)


In [45]:
for (x,y) in koordinatList:
  print(y)

15.2
102.3
186


In [46]:
for (x,y) in koordinatList:
  print(x)

10.2
30.2
94


In [47]:
sozluk = {"muz": 150, "portakal" : 200, "elma":400}


In [48]:
for (anahtar, deger) in sozluk.items():
  print(deger)

150
200
400


In [49]:
myTuple

(12, 2, 3, 4, 5, 6)

In [50]:
for numara in myTuple:
  if numara==5:
    break
  print(numara)

12
2
3
4


In [51]:
for numara in myTuple:
  if numara == 12:
    continue

In [52]:
print(numara)

6


In [53]:
x = 0
while x<10:
  print(x)
  x = x+1

0
1
2
3
4
5
6
7
8
9


In [54]:
benimListem

[10, 20, 30, 40, 50]

In [55]:
benimListem.pop()

50

In [56]:
benimListem

[10, 20, 30, 40]

In [57]:
benimListem.append(509)

In [58]:
benimListem

[10, 20, 30, 40, 509]

In [59]:
while 30 in benimListem:
  print("30 listede")
  benimListem.pop()

30 listede
30 listede
30 listede


In [60]:
benimListem

[10, 20]

In [61]:
list

list

In [62]:
list(range(5,21,4))

[5, 9, 13, 17]

In [63]:
index = 0
for numara in list(range(5,15)):
  print(f"güncel numara: {numara} güncel index: {index}")
  index +=1
print(numara)

güncel numara: 5 güncel index: 0
güncel numara: 6 güncel index: 1
güncel numara: 7 güncel index: 2
güncel numara: 8 güncel index: 3
güncel numara: 9 güncel index: 4
güncel numara: 10 güncel index: 5
güncel numara: 11 güncel index: 6
güncel numara: 12 güncel index: 7
güncel numara: 13 güncel index: 8
güncel numara: 14 güncel index: 9
14


In [64]:
for (index, numara) in enumerate(list(range(5,15))):
  print(numara)

5
6
7
8
9
10
11
12
13
14


In [65]:
from random import randint
randint(10,100)


98

In [66]:
newList = list(range(0,10))
newList[randint(0,9)]

6

In [67]:
newList

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [68]:
from random import shuffle
shuffle(newList)
newList

[2, 7, 0, 4, 5, 9, 1, 3, 6, 8]

In [69]:
yemekListesi = ["muz", "ananaas", "elma"]
kaloriListesi = [100,200,300]
gunListe = ["pazartesi", "salı","çarşamba"]
zipList=list(zip(yemekListesi, gunListe,kaloriListesi)) #listeleri birleştirmek için kull

In [70]:
zipList

[('muz', 'pazartesi', 100),
 ('ananaas', 'salı', 200),
 ('elma', 'çarşamba', 300)]

In [71]:
for eleman in zipList:
  print(type(eleman))

<class 'tuple'>
<class 'tuple'>
<class 'tuple'>


In [72]:
zipList

[('muz', 'pazartesi', 100),
 ('ananaas', 'salı', 200),
 ('elma', 'çarşamba', 300)]

In [73]:
for eleman in zipList:
  print(type(eleman))

<class 'tuple'>
<class 'tuple'>
<class 'tuple'>


In [74]:
zipList

[('muz', 'pazartesi', 100),
 ('ananaas', 'salı', 200),
 ('elma', 'çarşamba', 300)]

In [75]:
listeOrnegi = []

In [76]:
string = "baris"

In [77]:
for harf in string:
  listeOrnegi.append(harf)

In [78]:
listeOrnegi

['b', 'a', 'r', 'i', 's']

In [79]:
yeniDeger = "atıl"
yeniListe = [eleman for eleman in yeniDeger]

In [80]:
yeniListe

['a', 't', 'ı', 'l']

In [81]:
isim = "isimsiz"
isim.upper()

'ISIMSIZ'

In [82]:
def fonksiyon():
  print("fonksiyon")

In [83]:
fonksiyon()

fonksiyon


In [84]:
def merhabaDunya(yazdir):
  print("merhaba")
  print(yazdir)

merhabaDunya("asd")

merhaba
asd


In [85]:
def merhaba( isim = "barış"):
  print("merhaba")
  print(isim)

In [86]:
merhaba()

merhaba
barış


In [87]:
merhaba("asd")

merhaba
asd


In [88]:
def toplama(s1,s2):
  sonuc = s1+s2
  print(sonuc)

toplama(10,20)

30


In [89]:
def superT(num1, num2,num3):
  print(num1+num2+num3)

superT(10,20,30)

60


In [90]:
degisken = toplama(10,20)


30


In [91]:
type(degisken)

NoneType

In [92]:
def dondurTopla(num1, num2):
  return num1+num2

In [93]:
yeni = dondurTopla(10,10)

In [94]:
yeni

20

In [95]:
type(yeni)

int

In [96]:
def kontrolFonksiyon(s):
  if s == "barış":
    print("doğru")
  else:
    print("hata")

In [97]:
kontrolFonksiyon("")

hata


In [98]:
def yeniToplam(*args):
  return sum(args)
yeniToplam(1,2,3,4,5)

15

In [99]:
def ornekFonksiyon(**kwargs):
  print(kwargs)

In [100]:
type=ornekFonksiyon(muz = 100, elma= 200, ananas = 300)

{'muz': 100, 'elma': 200, 'ananas': 300}


In [101]:
def testKwargs(**kwargs):
 return(kwargs)


In [102]:
testKwargs(muz=100, elma=200,ananas=300)

{'muz': 100, 'elma': 200, 'ananas': 300}

In [103]:
def my_sum(my_integers):
  result=0
  for x in my_integers:
    result +=x
  return result

list_of_integers = [1,2,3]
print(my_sum(list_of_integers))

6


In [104]:
def new_my_sum(*args):
  result = 0
  for x in args:
    result += x
  return result

new_my_sum(1,2,3,4,5)

15

In [105]:
def kwargsTest(**kwargs):
  return(kwargs)

In [106]:
def bolmeIslemi(numara):
  return numara / 2

bolmeIslemi(20)

10.0

In [107]:
benimListem

[10, 20]

In [108]:
benimListem = [1,2,3,4,5,6,7,8,9,10]
yeniListe = []
for eleman in benimListem:
  bolmeIslemi(eleman)
  yeniListe.append(bolmeIslemi(eleman))
yeniListe

[0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0]

In [109]:
list(map(bolmeIslemi, benimListem))

[0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0]

In [110]:
def kontrolFonksiyonu(string):
  return "a" in string

In [111]:
kontrolFonksiyon("atıl")

hata


In [112]:
def kontrolFonksiyonu(string):
  return "a" in string

In [113]:
kontrolFonksiyonu("eqwe")

False

In [114]:
mylist = ["apple", "banana", "cherry"]

In [115]:
list(map(kontrolFonksiyonu, mylist))

[True, True, False]

In [116]:
list(filter(kontrolFonksiyonu,mylist))

['apple', 'banana']

In [117]:
carpma = lambda numara : numara *3

In [118]:
carpma(10)

30

In [119]:
list(map(lambda numara: numara * 4, mylist))

['appleappleappleapple',
 'bananabananabananabanana',
 'cherrycherrycherrycherry']

In [120]:
#scope
numara = 20

def carpma(rakam):
  numara = 10
  return numara*rakam
carpma(5)

50

In [121]:
print(numara)

20


In [122]:
isim = "Barış"

def isimFonk():
  isim = "Erhan"

  def icFonk():
    isim = "Ölmez"
    print(isim)

  icFonk()

isimFonk()

Ölmez


In [123]:
print(isim)

Barış


In [124]:

y  = 10

def deneme():
  global y
  y = 5
  print(y)

In [125]:
y

10

In [126]:
def hesapla(**kwargs):
  return kwargs

In [127]:
def hesapla(a, b, islem):
  if islem == "+":
    return (str(a)+ " + "+ str(b) + " = " + str(a+b))
  if islem == "-":
    return (str(a) + " - " + str(b) + " = " + str(a-b))
  if islem == "*":
    return (str(a) + " * " + str(b) + " = " + str(a*b))
  if islem == "/":
    return (str(a)+ " / "+ str(b) + " = " + str(a/b))
  
  a = int(input("s1 : "))
  b = int(input("s2 :"))
  islem = input("+-*/ gir: ")
  hesapla(a,b, islem)


In [128]:
10



10

In [129]:
10230123

10230123

In [130]:
def hesapla(a, b, islem):
  if islem == "+":
    return (str(a)+ " + "+ str(b) + " = " + str(a+b))
  if islem == "-":
    return (str(a) + " - " + str(b) + " = " + str(a-b))
  if islem == "*":
    return (str(a) + " * " + str(b) + " = " + str(a*b))
  if islem == "/":
    return (str(a)+ " / "+ str(b) + " = " + str(a/b))
  
  a = int(input("s1 : "))
  b = int(input("s2 :"))
  islem = input("+-*/ gir: ")
  hesapla(a,b , islem)

In [131]:
class SuperKahraman():
  def __init__(self, isimInput, yasInput, meslekInput):
    print("init çağrıldı")
    self.isim = isimInput
    self.yas = yasInput
    self.meslek = meslekInput



In [132]:
class SuperKahraman():


    def __init__(self, isim, yas, meslek):
        print("init oluşturuldu")
        self.isim = isim
        self.yas = yas
        self.meslek = meslek

        
    def ornekMethod(self):
        print(f" ben süper kahramanım ve mesleğim: {self.meslek}" )

superman = SuperKahraman("Superman",30,"Çoban")

superman.isim = "Clark kent"
superman.isim
superman.ornekMethod()

init oluşturuldu
 ben süper kahramanım ve mesleğim: Çoban


In [133]:
class Kopek():
  yilCarpani = 7
  def __init__(self, yas=99):
    self.yas = yas

  def insanYasiniHesapla(self, yas=10):
    return self.yas * self.yilCarpani

kopek = Kopek(3)
kopek.yas

kopek.insanYasiniHesapla()

21

In [134]:
# Inheritance (KALITIM MİRAS)

In [135]:
class Hayvan():
  def __init__(self):

    print("hayvan sınıfı init çağırıldı")

  @classmethod
  def method1(self):
    
    print(f"Hayvan sınıfından method1 çağırıldı.** ")
  
  def method2(self):
    print("Hayvan sınıfından method2 çağırıldı**")

  def method3(self):
    print("miyavla")

hayvanOlustur = Hayvan()

hayvanOlustur.method1()
hayvanOlustur.method2()

class Kedi(Hayvan):
  def __init__(self):
    Hayvan.__init__(self)
    print("kedi sınıfı init çağırıldı.")

kediOlustur = Kedi()
kediOlustur.method1()
kediOlustur.method2()
kediOlustur.method3()

hayvan sınıfı init çağırıldı
Hayvan sınıfından method1 çağırıldı.** 
Hayvan sınıfından method2 çağırıldı**
hayvan sınıfı init çağırıldı
kedi sınıfı init çağırıldı.
Hayvan sınıfından method1 çağırıldı.** 
Hayvan sınıfından method2 çağırıldı**
miyavla


In [136]:
Hayvan.method1()

Hayvan sınıfından method1 çağırıldı.** 


In [137]:
import numpy as np

# numpy array

liste = [20,30,40]

np.array(liste)  # convertir une liste en un tableau numérique de numpy
matrixListesi = [[10,20,30,40], [20,30,40], [30,40,50]]
matrixListesi[1][0]





20

In [138]:
yeniListe = [
  [3,2],
  [2,1],
  [1,2],
    ]
np.array(yeniListe)

array([[3, 2],
       [2, 1],
       [1, 2]])

In [139]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [140]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [141]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [142]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [143]:
np.eye(5
       )

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [144]:
# SERIES
import pandas as pd
data = np.random.rand(4,3)

dataFrame = pd.DataFrame(data)
dataFrame

0         1         2
0  0.762136  0.847189  0.759581
1  0.662688  0.153221  0.937673
2  0.274780  0.756323  0.629989
3  0.688923  0.096406  0.554618

In [145]:
yeniDataFrame = pd.DataFrame(data, index=["atil", "zeynep", "atlas", "mehmet"], columns=["maas", "yas", "calisma saati"])
yeniDataFrame

maas       yas  calisma saati
atil    0.762136  0.847189       0.759581
zeynep  0.662688  0.153221       0.937673
atlas   0.274780  0.756323       0.629989
mehmet  0.688923  0.096406       0.554618

In [146]:
yeniDataFrame["yas"]



atil      0.847189
zeynep    0.153221
atlas     0.756323
mehmet    0.096406
Name: yas, dtype: float64

In [147]:
yeniDataFrame.iloc[0]

maas             0.762136
yas              0.847189
calisma saati    0.759581
Name: atil, dtype: float64

In [149]:
yeniDataFrame

maas       yas  calisma saati
atil    0.762136  0.847189       0.759581
zeynep  0.662688  0.153221       0.937673
atlas   0.274780  0.756323       0.629989
mehmet  0.688923  0.096406       0.554618

In [152]:
yeniDataFrame["emeklilik yasi"] = yeniDataFrame["yas"] + yeniDataFrame["yas"]
yeniDataFrame

maas       yas  calisma saati  emeklilik yasi
atil    0.762136  0.847189       0.759581        1.694379
zeynep  0.662688  0.153221       0.937673        0.306442
atlas   0.274780  0.756323       0.629989        1.512646
mehmet  0.688923  0.096406       0.554618        0.192811

In [154]:
yeniDataFrame.drop("emeklilik yasi", axis=1)

maas       yas  calisma saati
atil    0.762136  0.847189       0.759581
zeynep  0.662688  0.153221       0.937673
atlas   0.274780  0.756323       0.629989
mehmet  0.688923  0.096406       0.554618

In [155]:
yeniDataFrame.drop("mehmet")

maas       yas  calisma saati  emeklilik yasi
atil    0.762136  0.847189       0.759581        1.694379
zeynep  0.662688  0.153221       0.937673        0.306442
atlas   0.274780  0.756323       0.629989        1.512646

In [156]:
yeniDataFrame

maas       yas  calisma saati  emeklilik yasi
atil    0.762136  0.847189       0.759581        1.694379
zeynep  0.662688  0.153221       0.937673        0.306442
atlas   0.274780  0.756323       0.629989        1.512646
mehmet  0.688923  0.096406       0.554618        0.192811

In [157]:
yeniDataFrame.drop("emeklilik yasi", axis=1, inplace=True)

In [158]:
yeniDataFrame

maas       yas  calisma saati
atil    0.762136  0.847189       0.759581
zeynep  0.662688  0.153221       0.937673
atlas   0.274780  0.756323       0.629989
mehmet  0.688923  0.096406       0.554618

In [160]:
yeniDataFrame.loc["atil"]["yas"]

0.8471893635818335

In [161]:
yeniDataFrame.loc["atlas", "yas"]

0.7563231375320421

In [163]:
booleanFrame = yeniDataFrame < 0

In [164]:
booleanFrame

maas    yas  calisma saati
atil    False  False          False
zeynep  False  False          False
atlas   False  False          False
mehmet  False  False          False

In [167]:
yeniDataFrame[booleanFrame]

maas  yas  calisma saati
atil     NaN  NaN            NaN
zeynep   NaN  NaN            NaN
atlas    NaN  NaN            NaN
mehmet   NaN  NaN            NaN

In [168]:
yeniDataFrame[yeniDataFrame <0]

maas  yas  calisma saati
atil     NaN  NaN            NaN
zeynep   NaN  NaN            NaN
atlas    NaN  NaN            NaN
mehmet   NaN  NaN            NaN

In [172]:
yeniDataFrame[yeniDataFrame["yas"] >0.111111]

maas       yas  calisma saati
atil    0.762136  0.847189       0.759581
zeynep  0.662688  0.153221       0.937673
atlas   0.274780  0.756323       0.629989

In [173]:
yeniDataFrame

maas       yas  calisma saati
atil    0.762136  0.847189       0.759581
zeynep  0.662688  0.153221       0.937673
atlas   0.274780  0.756323       0.629989
mehmet  0.688923  0.096406       0.554618

In [174]:
yeniDataFrame.reset_index()

index      maas       yas  calisma saati
0    atil  0.762136  0.847189       0.759581
1  zeynep  0.662688  0.153221       0.937673
2   atlas  0.274780  0.756323       0.629989
3  mehmet  0.688923  0.096406       0.554618

In [175]:
yeniDataFrame

maas       yas  calisma saati
atil    0.762136  0.847189       0.759581
zeynep  0.662688  0.153221       0.937673
atlas   0.274780  0.756323       0.629989
mehmet  0.688923  0.096406       0.554618

In [176]:
yeniIndexListesi = ["ati", "zey", "atl", "meh"]

In [177]:
yeniDataFrame["yeni ındeks"] = yeniIndexListesi

In [178]:
yeniDataFrame

maas       yas  calisma saati yeni ındeks
atil    0.762136  0.847189       0.759581         ati
zeynep  0.662688  0.153221       0.937673         zey
atlas   0.274780  0.756323       0.629989         atl
mehmet  0.688923  0.096406       0.554618         meh

In [179]:
yeniDataFrame.set_index("yeni ındeks")

maas       yas  calisma saati
yeni ındeks                                   
ati          0.762136  0.847189       0.759581
zey          0.662688  0.153221       0.937673
atl          0.274780  0.756323       0.629989
meh          0.688923  0.096406       0.554618

In [180]:
yeniDataFrame

maas       yas  calisma saati yeni ındeks
atil    0.762136  0.847189       0.759581         ati
zeynep  0.662688  0.153221       0.937673         zey
atlas   0.274780  0.756323       0.629989         atl
mehmet  0.688923  0.096406       0.554618         meh

In [181]:
yeniDataFrame.set_index("yeni ındeks", inplace=True)

In [182]:
yeniDataFrame

maas       yas  calisma saati
yeni ındeks                                   
ati          0.762136  0.847189       0.759581
zey          0.662688  0.153221       0.937673
atl          0.274780  0.756323       0.629989
meh          0.688923  0.096406       0.554618

In [183]:
yeniDataFrame.loc["ati"]

maas             0.762136
yas              0.847189
calisma saati    0.759581
Name: ati, dtype: float64

In [184]:
ilkIndeksler = ["Simpson", "Simpson", "Simpson", "South Park","South Park","South Park"]

In [185]:
icIndeksler = ["Homer", "Bart", "Marge", "Cartman", "Kenny", "Kyle"]

In [186]:
birlesmisIndeks = list(zip(ilkIndeksler, icIndeksler))

In [187]:
birlesmisIndeks

[('Simpson', 'Homer'),
 ('Simpson', 'Bart'),
 ('Simpson', 'Marge'),
 ('South Park', 'Cartman'),
 ('South Park', 'Kenny'),
 ('South Park', 'Kyle')]

In [188]:
birlesmisIndeks = pd.MultiIndex.from_tuples(birlesmisIndeks)

In [195]:
birlesmisIndeks


MultiIndex([(   'Simpson',   'Homer'),
            (   'Simpson',    'Bart'),
            (   'Simpson',   'Marge'),
            ('South Park', 'Cartman'),
            ('South Park',   'Kenny'),
            ('South Park',    'Kyle')],
           )

In [196]:
benimCizgiFilmListem = [[40, "A"], [30,"B"], [30, "C"], [30, "D"], [40, "E"], [3, "F"]]

In [198]:
benimCizgiFilmNumpyDizisi = np.array(benimCizgiFilmListem)

In [200]:
benimCizgiFilmDataFrame = pd.DataFrame(benimCizgiFilmNumpyDizisi, index = birlesmisIndeks, columns=["yas", "meslek"])

In [201]:
benimCizgiFilmDataFrame

yas meslek
Simpson    Homer    40      A
           Bart     30      B
           Marge    30      C
South Park Cartman  30      D
           Kenny    40      E
           Kyle      3      F

In [203]:
benimCizgiFilmDataFrame.loc["Simpson"]

yas meslek
Homer  40      A
Bart   30      B
Marge  30      C

In [204]:
benimCizgiFilmDataFrame.loc["South Park"]

yas meslek
Cartman  30      D
Kenny    40      E
Kyle      3      F

In [205]:
benimCizgiFilmDataFrame.loc["South Park"].loc["Kenny"]

yas       40
meslek     E
Name: Kenny, dtype: object

In [206]:
benimCizgiFilmDataFrame.index.names = ["film adi", "isim"]

In [207]:
benimCizgiFilmDataFrame

yas meslek
film adi   isim              
Simpson    Homer    40      A
           Bart     30      B
           Marge    30      C
South Park Cartman  30      D
           Kenny    40      E
           Kyle      3      F